kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: ZQnCYd5wfjlntjDGIamnaS1Ik+CN/zzwWIyq5a3pPBA=
      - identity: {}
